service: lijstje
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
functions:
  api:
    handler: dist/server.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
